name: belajar ci dengan github action
on:
  push:
    branches: ["devlop"]
  pull_request:
    branches: ["devlop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Setup Database
        run: |
          php -r "file_exists('database/db.sqlite') || touch('database/db.sqlite');"
          php artisan migrate

      - name: Execute Tests
        run: php artisan test
